INSERT INTO author(first_name, second_name, birthday) VALUES ('Joanne', 'Rowling', '1965-07-31');
INSERT INTO author(first_name, second_name, birthday) VALUES ('Terry', 'Pratchett', '1948-04-28');
INSERT INTO author(first_name, second_name, birthday) VALUES ('John Ronald Reuel', 'Tolkien', '1892-01-03');
INSERT INTO author(first_name, second_name, birthday) VALUES ('George', 'Martin', '1948-09-20');
INSERT INTO author(first_name, second_name, birthday) VALUES ('Howard Phillips', 'Lovecraft', '1890-08-20');
INSERT INTO book(name, description, publication_date, author_id) VALUES ('Harry Potter and the Philosopher''s Stone', 'Harry Potter and the Philosopher''s Stone', '1997-06-26', 1);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('Harry Potter and the Chamber of Secrets', 'Harry Potter and the Chamber of Secrets', '1998-07-02', 1);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('Harry Potter and the Prisoner of Azkaban', 'Harry Potter and the Prisoner of Azkaban', '1999-07-08', 1);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('Harry Potter and the Goblet of Fire', 'Harry Potter and the Goblet of Fire', '2000-06-08', 1);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('Harry Potter and the Order of the Phoenix', 'Harry Potter and the Order of the Phoenix', '2003-06-21', 1);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('Harry Potter and the Half-Blood Prince', 'Harry Potter and the Half-Blood Prince', '2005-06-16', 1);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('Harry Potter and the Deathly Hallows', 'Harry Potter and the Deathly Hallows', '2007-07-21', 1);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('The Colour of Magic', 'The Colour of Magic', '1983-11-24', 2);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('The Light Fantastic', 'The Light Fantastic', '1986-07-21', 2);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('The Lord of the Rings: The Fellowship of the Ring', 'The Lord of the Rings: The Fellowship of the Ring', '1954-07-29', 3);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('The Lord of the Rings: The Two Towers', 'The Lord of the Rings: The Two Towers', '1954-11-11', 3);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Return of the King', '1955-10-20', 3);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('A Game of Thrones', 'A Game of Thrones', '1996-08-01', 4);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('A Clash of Kings ', 'A Clash of Kings ', '1998-11-16', 4);
INSERT INTO book(name, description, publication_date, author_id) VALUES ('The Call of Cthulhu and Other Weird Stories', 'The Call of Cthulhu and Other Weird Stories', '1999-10-01', 5);
