version: "3"
services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: consul agent -server -bootstrap-expect=1 -ui -data-dir /consul/data -client=0.0.0.0
    restart: on-failure
    volumes:
      - ./config-data:/consul/data
  mongo-db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"