// GET BOOK LIST AND DELETE BOOKS

export const REQUEST_BOOKS = 'REQUEST_BOOKS';
export const REQUEST_DELETE_BOOK = 'REQUEST_DELETE_BOOK';

export const RECEIVE_BOOKS = 'RECEIVE_BOOKS';
export const SUCCESS_DELETE_BOOK = 'SUCCESS_DELETE_BOOK';

export const ERROR_RECEIVING_BOOKS = 'ERROR_RECEIVING_BOOKS';
export const ERROR_DELETING_BOOK = 'ERROR_DELETING_BOOK';