// CREATE AND EDIT BOOK

export const REFRESH_STORE = 'REFRESH_STORE';

export const CREATING_BOOK = 'CREATING_BOOK';
export const EDITING_BOOK = 'EDITING_BOOK';
export const FETCHING_BOOK = "FETCHING_BOOK";

export const SUCCESS_CREATING_BOOK = 'SUCCESS_CREATING_BOOK';
export const SUCCESS_EDITING_BOOK = 'SUCCESS_EDITING_BOOK';
export const RECEIVE_BOOK = 'RECEIVE_BOOK';

export const ERROR_CREATING_BOOK = 'ERROR_CREATING_BOOKS';
export const ERROR_EDITING_BOOK = 'ERROR_EDITING_BOOK';
export const ERROR_RECEVING_BOOK = 'ERROR_RECEVING_BOOK';